apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: springcommunity/spring-petclinic-discovery-server
          ports:
            - containerPort: 8761
          resources:
            limits:
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 5
            periodSeconds: 5
